sudo: false
language: python
python:
- 2.6
- 2.7
- 3.3
- 3.4
- nightly
- pypy

env:
  matrix:
    - WEBFRAMEWORK=django-1.4
    - WEBFRAMEWORK=django-1.5
    - WEBFRAMEWORK=django-1.6
    - WEBFRAMEWORK=django-1.7
    - WEBFRAMEWORK=django-1.8
    - WEBFRAMEWORK=django-master
    - WEBFRAMEWORK=flask-0.8
    - WEBFRAMEWORK=flask-0.9
    - WEBFRAMEWORK=flask-0.10
  global:
    - PIP_CACHE="$HOME/.pip_cache"'

matrix:
  exclude:
  - python: 2.6
    env: DJANGO=1.7
  - python: 2.6
    env: DJANGO=1.8
  - python: 2.6
    env: DJANGO=master
  - python: 3.3
    env: DJANGO=1.4
  - python: 3.4
    env: DJANGO=1.4
  - python: nightly
    env: DJANGO=1.4
  allow_failures:
  - env: DJANGO=master
  - python: nightly

addons:
  apt:
    packages:
      - libevent-dev
      - libzmq3-dev
  postgresql: "9.3"

cache:
  directories:
    - $HOME/.pip_cache

before_install:
  - mkdir -p $PIP_CACHE

install:
- pip install -U pip
- pip install -r test_requirements/requirements-$WEBFRAMEWORK.txt --cache-dir $PIP_CACHE
- pip install -r test_requirements/requirements-python-$(python --version 2>&1 | awk -F'[ |.]' 'NR==1{ print $2 }').txt --cache-dir $PIP_CACHE

before_script:
  - psql -c 'create database opbeat_test;' -U postgres

script:
- make test

notifications:
  email: false
  slack:
    secure: LcTTbTj0Px0/9Bs/S/uwbhkdULlj1YVdHnU8F/kOa3bq2QdCTptqB719r6BnzHvW+QGyADvDZ25UncVXFuLuHY67ZYfmyZ/H2cj0nrRSuYdPct0avhVbT/3s50GlNWK5qkfZDuqw6szYTFrgFWJcr5dl7Zf6Vovcvd38uaYOdno=

services:
  - redis-server
  - memcached
