language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1
  - DJANGO=1.4.13
  - DJANGO=1.5.8
  - DJANGO=1.6.5
install:
  - sudo apt-get install libevent-dev
  - sudo apt-get install libzmq3-dev
  - sudo pip install Django==$DJANGO --use-mirrors
script:
  - make test
notifications:
  email: false
