language: python
python:
  - "2.6"
  - "2.7"
  env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1
  - DJANGO=1.4.4
install:
  - sudo apt-get install libevent-dev
  - sudo aot-get install libzmq3-dev
  - sudo pip install Django==$DJANGO --use-mirrors
  - sudo pip install -e . --use-mirrors
script:
  - make test
notifications:
  email: false
