language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.1
install:
  - sudo apt-get install libevent-dev
  - sudo pip install Django==$DJANGO --use-mirrors
  - sudo pip install pep8 --use-mirrors
  - sudo pip install https://github.com/dcramer/pyflakes/tarball/master
  - sudo pip install -e . --use-mirrors
script:
  - "sudo pep8 --ignore=E501,E225 raven"
  - sudo pyflakes -x W raven
  - sudo python setup.py test
notifications:
  irc:
    channels: "irc.freenode.org#sentry"
    on_success: change
    on_failure: change