sudo: false
language: python
python:
- 2.6
- 2.7
- 3.3
- 3.4
- pypy

env:
  matrix:
    - DJANGO=1.4
    - DJANGO=1.5
    - DJANGO=1.6
    - DJANGO=1.7
    - DJANGO=1.8
    - DJANGO=master
  global:
    - PIP_CACHE="$HOME/.pip_cache"'

matrix:
  exclude:
  - python: 2.6
    env: DJANGO=1.7
  - python: 2.6
    env: DJANGO=1.8
  - python: 2.6
    env: DJANGO=master
  - python: 3.3
    env: DJANGO=1.4
  - python: 3.4
    env: DJANGO=1.4
  allow_failures:
  - env: DJANGO=master

addons:
  apt:
    packages:
      - libevent-dev
      - libzmq3-dev

cache:
  directories:
    - $HOME/.pip_cache

before_install:
  - mkdir -p $PIP_CACHE

install:
- pip install -U pip
- pip install -r test_requirements/requirements-django-$DJANGO.txt --cache-dir $PIP_CACHE
- pip install -r test_requirements/requirements-python-$(python --version 2>&1 | awk -F'[ |.]' 'NR==1{ print $2 }').txt --cache-dir $PIP_CACHE

script:
- make test

notifications:
  email: false
  slack:
    secure: LcTTbTj0Px0/9Bs/S/uwbhkdULlj1YVdHnU8F/kOa3bq2QdCTptqB719r6BnzHvW+QGyADvDZ25UncVXFuLuHY67ZYfmyZ/H2cj0nrRSuYdPct0avhVbT/3s50GlNWK5qkfZDuqw6szYTFrgFWJcr5dl7Zf6Vovcvd38uaYOdno=

services:
  - redis-server
  - memcached